version: '3.7'
services:
  php:
    volumes:
      - .:/var/www/html
      - $HOME/.composer/cache:/root/.composer/cache
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    ports:
      - '80:80'

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
