@startuml
class Sensor {
    Integer id
    String name
    SensorType type
    SensorStatus actualStatus
    Integer frequency
    Float threshold
}

class SensorType {
    Integer id
    String name
    SensorStatus[] possibleStatuses
}

class SensorStatus {
    Integer id
    String name
}

class SensorStatusHistory {
    Integer id
    Sensor sensor
    SensorStatus fromStatus
    SensorStatus toStatus
    DateTime timestamp
}

class Stereotype {
    Integer id
    SensorStatusHistory sensorStatusChange
    Integer dayOfMonth
    Integer dayOfWeek
    Time time
    Relevance relevance
}

class Relevance {
    Integer id
    String name
    NotificationType notificationType
    String notificationValue
}

class NotificationType {
    Integer id
    String name
}

Sensor "many" *-- "1" SensorType
Sensor "many" *-- "1" SensorStatus
SensorType "many" *-- "many" SensorStatus
SensorStatusHistory "many" *-- "1" Sensor
SensorStatusHistory "many" *-- "1" SensorStatus
Stereotype "many" *-- "1" SensorStatusHistory
Stereotype "many" *-- "1" Relevance
Relevance "many" *-- "1" NotificationType
@enduml